name: Migrate Secrets/Variables to GHE

on:
  push:
    branches:
      - chore/migrate-secrets-to-ghe

permissions: read-all

jobs:
  migrate-secrets:
    name: Migrate Secrets
    uses: Muon-space/muon-ci/.github/workflows/migrate_secrets.yml@v1
    with:
      github_target_org: Muon-Space
      target_api_url: 'https://api.muonspace.ghe.com'
      migrate_org_secrets: false
      upload_to_keeper: true
      dry_run: false
    secrets: inherit  # CRITICAL: This passes ALL repository secrets to the reusable workflow
